export { default as Character } from './Character'
export { default as Episode } from './Episode'
export { default as Home } from './Home'
export { default as Location } from './Location'
export { default as NotFound } from './NotFound'
