GET https://rickandmortyapi.com/api/
###
GET https://rickandmortyapi.com/api/episode
    ?page=2
###
GET https://rickandmortyapi.com/api/episode/2
###
GET https://rickandmortyapi.com/api/character/120
###
GET https://rickandmortyapi.com/api/location/12